# Generated by Django 5.1.6 on 2025-03-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='track',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='track',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='plans',
            field=models.CharField(choices=[('basic', 'Basic'), ('medium', 'Medium'), ('premium', 'Premium')], max_length=10),
        ),
        migrations.AlterField(
            model_name='track',
            name='last_played',
            field=models.DateField(blank=True, null=True),
        ),
    ]
