# Generated by Django 5.1.6 on 2025-06-18 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='status',
        ),
    ]
