# Generated by Django 5.1.6 on 2025-03-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_album_image_url_remove_artist_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
