# Generated by Django 5.1.6 on 2025-03-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_alter_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='plans',
        ),
        migrations.AddField(
            model_name='order',
            name='plans',
            field=models.ManyToManyField(to='musicapp.pricing'),
        ),
    ]
