# Generated by Django 5.1.6 on 2025-03-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0009_remove_order_plans_order_plans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='plans',
        ),
        migrations.AddField(
            model_name='order',
            name='plans',
            field=models.CharField(default='basic', max_length=100),
        ),
    ]
