# Generated by Django 5.1.6 on 2025-03-20 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0011_subscription_paymentid_alter_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.pricing'),
        ),
    ]
