# Generated by Django 5.1.6 on 2025-03-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0012_alter_order_plans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='plans',
            new_name='pricing',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='plans',
            new_name='pricing',
        ),
    ]
