# Generated by Django 5.1.6 on 2025-03-21 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0013_rename_plans_order_pricing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_order', to='musicapp.pricing'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_subscription', to='musicapp.pricing'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
