# Generated by Django 5.1.6 on 2025-03-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0014_alter_order_pricing_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=10),
        ),
    ]
