# Generated by Django 5.1.6 on 2025-05-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0015_pricing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='bill',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='paid', max_length=10),
        ),
    ]
